3 Crear endpoint para recibir JSON
db-training-etl/transform-microservice pull request #13
Opened 2022-10-20 14:45 UTC by anntGFT

2022-10-20 15:04 UTC, AxseGFT approved these changes

2022-10-20 15:17 UTC, gnugomez requested changes
Please check those things before merging

2022-10-20 15:17 UTC, gnugomez commented on src/main/java/com/db/transform/controller/TransformController.java
> +    @GetMapping(value = "/trades")
you should use ```/trades/saveFile``` or something like this as we said this morning

2022-10-20 15:17 UTC, gnugomez commented on src/main/java/com/db/transform/service/TransformService.java
> +    WebClient webClient;
This code will need to be refactored later to separate webClient to a repository and replace it with the correct things, so i think we can exclude this from this pr for now.

2022-10-20 15:17 UTC, gnugomez commented on src/main/resources/tradeName-cobdate.xml
> +<ArrayList>
While you use this file for testing purposes you should store this file in ```src/test/resources/...```

2022-10-20 15:18 UTC, Jubaal approved these changes

2022-10-21 10:04 UTC, gnugomez approved these changes

2022-10-21 10:04 UTC, merged